### PR TITLE
Added .env file

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
Solved #63 #64 #62

### CODE REVIEW

**Comment by mohit200008** [comment]
do make sure the app is working
and it doesn't crash

**Comment by Abhijeet-2003** [comment]
Yes it is working @mohit200008.

**Comment by Abhijeet-2003** [comment]
Can I create an issue to update the README.md and write about the env file over there.

**Comment by mohit200008** [comment]
> Can I create an issue to update the README.md and write about the env file over there.

you can directly put it

**Comment by Abhijeet-2003** [comment]
I'll send another pr for that. Kindly review and merge this one. @mohit200008

**Comment by Abhijeet-2003** [comment]
Please merge this @mohit200008, if reviewed.

**Comment by Abhijeet-2003** [comment]
@mohit200008. I have solved #64 issue too. Kindly review and merge.

**Comment by Abhijeet-2003** [comment]
Screenshot 2023-01-04 at 2 13 58 AM

**Comment by Abhijeet-2003** [comment]
@mohit200008.

**Comment by Abhijeet-2003** [comment]
I've solved #62 as well @mohit200008. Please review and merge.

**Comment by mohit200008** [comment]
@Abhijeet-2003   please add the credentials in the readme

**Comment by Abhijeet-2003** [comment]
Can I make a seperate issue for this and then send another pr ?
I'll make a .env.sample file for future contributors to refer along with the modifications in readme. @mohit200008

**Comment by mohit200008** [comment]
okay

**Comment by Abhijeet-2003** [comment]
I haven't received points yet @mohit200008. Kindly check.

**Pull request merged**
