### PR TITLE
Homepage in hindi converted named as HomeinHindi.js

### PR DESCRIPTION
**Pull request by Kanika637**

### CODE REVIEW

**Comment by mohit200008** [comment]
Can you share a sc @Kanika637 ??

**Comment by aktamoli0910** [comment]
@Kanika637 please share screenshots.

**Comment by Kanika637** [comment]
Well...I already send u the screenshots that day itself...

**Comment by mohit200008** [comment]
where did you send the screenshots???

**Comment by mohit200008** [comment]
@aktamoli0910  please check ???

**Comment by aktamoli0910** [comment]
@Kanika637 can you please share it again on the discord channel of the project?

**Comment by aktamoli0910** [comment]
Hello @Kanika637 can you please mail the screenshots at aktamoli0910@gmail.com so that we can review and merge your pr.

**Pull request closed without merging**
