### PR TITLE
Login

### PR DESCRIPTION
**Pull request by kanishak11-cyber**

### CODE REVIEW

**Comment by kanishak11-cyber** [comment]
there is a lot of work to do, i'm working on it

**Comment by kanishak11-cyber** [comment]
frontend of login page is completed and it can  create the user

review the web page

**Comment by mohit200008** [comment]
can you send a sc of the login and signup pages ????

**Comment by kanishak11-cyber** [comment]
image
image

**Comment by kanishak11-cyber** [comment]
I used firebase to create the new users profile 
for creating  new members u have to simply write the email and password and click on the create new account

**Comment by mohit200008** [comment]
Can you increase the width of the form and the borders can be a little bold.

**Comment by kanishak11-cyber** [comment]
image

is it okay or I have to do made other changes

**Comment by mohit200008** [comment]
The content inside the borders should be center aligned

**Comment by mohit200008** [comment]
And can you make the design better with the border radius of the sign in button increased

**Comment by kanishak11-cyber** [comment]
ya sure ill made the changes tomorrow  is there any way where i can contact  for proper advices

**Comment by kanishak11-cyber** [comment]
image

**Comment by kanishak11-cyber** [comment]
image

I made the changes

**Comment by mohit200008** [comment]
> ya sure ill made the changes tomorrow is there any way where i can contact for proper advices

Yeah , you can connect on discord anytime

**Comment by mohit200008** [comment]
There are some merge conflicts on this one . Please review the code 
And the design seems a bit monotonous , Can you please redesign it???

**Comment by mohit200008** [comment]
> There are some merge conflicts on this one . Please review the code And the design seems a bit monotonous , Can you please redesign it???

https://www.figma.com/file/DKdAeAkhaApFGUfDmj0GBX/FoodSaver-Login%2Fsignup?node-id=0%3A1 you can make this design @kanishak11-cyber

**Comment by mohit200008** [comment]
@kanishak11-cyber  when you're done , make a new pr i am closing this one

**Comment by kanishak11-cyber** [comment]
> @kanishak11-cyber  when you're done , make a new pr i am closing this one 

Okay sir,  
But i did find the conflict in NavBar css

**Comment by mohit200008** [comment]
> > @kanishak11-cyber  when you're done , make a new pr i am closing this one
> 
> Okay sir, But i did find the conflict in NavBar css

Resolve it and if user is not logged in , the add food page should not be visible

**Pull request closed without merging**
