### PR TITLE
solved issues #4, #35, #51, #57

### PR DESCRIPTION
**Pull request by Abhijeet-2003**
made the website responsive, fixed the styles on the recipe page where the title was overlapping, made the recipe card title smaller and the content is not overlapping anymore for any screen size, reduced the ingredients' weight to 2 decimal places as previously it was going past the border of its container.

### CODE REVIEW

**Comment by mohit200008** [comment]
there is merge conflict in this

**Comment by Abhijeet-2003** [comment]
I'm not getting the option to resolve the conflicts.

**Comment by Abhijeet-2003** [comment]
Resolved conflicts.

**Comment by mohit200008** [comment]
can you send a screen recording just to see if its working???

**Comment by Abhijeet-2003** [comment]
the video size limit is 10MB, showing every single page won't be possible in such a short video.

**Comment by Abhijeet-2003** [comment]
https://user-images.githubusercontent.com/108492066/208762009-4efdc0bc-8a93-447b-aee0-93fb6170cd9a.mov

**Pull request merged**
