### PR TITLE
signin/signup complete

### PR DESCRIPTION
**Pull request by kanishak11-cyber**
image
image

### CODE REVIEW

**Comment by kanishak11-cyber** [comment]
otp part is also done 

image
image
image

**Comment by mohit200008** [comment]
No need to show email input on otp  when user clicks login to otp , the input boxes and send otp button should appear asking for otp

**Comment by mohit200008** [comment]
And the boxes for otp should be more visible and appealing

**Comment by kanishak11-cyber** [comment]
image
image
image
I put some button and made the change all you mentioned

**Pull request merged**
